### ISSUE TITLE
Contribute to this project, Requirement: Good knowledge of Bash Script.

### ISSUE THREAD

**Issue by warisreshi** [warisreshi/packageumbrella#1]

**Comment by warisreshi** [comment]
If anyone is looking to contribute, please leave a comment or contact me at insta/twitter @warisreshi.

**Comment by RishiKumarRay** [comment]
@warisreshi i would love to contribute

**Comment by warisreshi** [comment]
@RishiKumarRay then please talk to me on twitter/insta username : @warisreshi.
